(function () {
  const statusCardLabels = {
    running: 'RUNNING',
    stopped: 'STOPPED',
    error: 'ERROR',
    starting: 'STARTING',
    stopping: 'STOPPING',
  };

  window.BotPanelText = {
    meta: {
      title: '🤖 Bot Panel',
    },
    topbar: {
      dockerConnected: 'Docker Conectado',
      stopAll: '■ Parar todos',
      stoppingAll: '⏳ Parando...',
      stopAllTitle: 'Parar todos los bots activos',
      runningSuffix: 'en ejecución',
      totalSuffix: 'bots',
    },
    nav: {
      bots: '⬡ Bots',
      multiConsole: '⊞ Multi-Consola',
    },
    sidebar: {
      title: 'Bots',
      newBot: '+ Nuevo Bot',
      searchPlaceholder: 'Buscar bots...',
      noResults: 'No se encontraron bots',
      noDescription: 'Sin descripción',
      quickRunTitle: 'Ejecutar',
      editDescriptionTitle: 'Editar descripción',
      deleteTitle: 'Eliminar',
    },
    emptyState: {
      title: 'Ningún bot seleccionado',
      subtitle: 'Selecciona un bot del panel lateral o crea uno nuevo',
    },
    workspace: {
      saved: 'Guardado',
      unsaved: 'Cambios sin guardar',
      saveButton: '💾 Guardar',
      runButton: '▶ Ejecutar',
      stopButton: '■ Detener',
      restartButton: '↺ Reiniciar',
      editorTab: 'Editor de Código',
      logsTab: 'Registros',
      containerLabel: 'Contenedor:',
      activeLabel: 'Activo:',
      cpuLabel: 'CPU:',
      memLabel: 'MEM:',
      activeRunning: 'EN EJECUCIÓN',
      activeError: 'ERROR',
      activeStopped: 'DETENIDO',
    },
    logs: {
      title: 'Salida de Consola',
      filterAll: 'ALL',
      filterStdout: 'STDOUT',
      filterStderr: 'STDERR',
      clear: 'Limpiar',
      empty: 'Sin salida aún. Ejecuta un bot para ver los registros.',
    },
    multiConsole: {
      title: '// Multi-Consola',
      layoutAuto: '⊞ Auto',
      layoutAutoTitle: 'Cuadrícula automática',
      layoutOneColumnTitle: 'Una columna',
      layoutTwoColumnsTitle: 'Dos columnas',
      layoutThreeColumnsTitle: 'Tres columnas',
      clearAll: '✕ Limpiar todo',
      clearAllTitle: 'Limpiar todas las consolas',
      refresh: '↺ Actualizar',
      refreshTitle: 'Actualizar bots activos',
      emptyTitle: 'No hay bots activos',
      emptySubtitle: 'Inicia un bot desde la vista Bots para ver su consola aquí',
      open: '↗ Abrir',
      connecting: 'Conectando...',
      botStopped: 'Bot detenido',
      linesLabel: 'Líneas',
      containerLabel: 'Contenedor',
      clear: 'Limpiar',
      cleared: 'Limpiado',
      statusCardLabels,
    },
    modals: {
      cancel: 'Cancelar',
      save: 'Guardar',
      newBot: {
        title: '// Crear Nuevo Bot',
        nameLabel: 'Nombre del Bot',
        namePlaceholder: 'mi_bot_increible',
        nameHint: 'Solo letras, números y guiones bajos. Será el nombre del directorio.',
        descriptionLabel: 'Descripción (opcional)',
        descriptionPlaceholder: '¿Qué hace este bot?',
        templateLabel: 'Plantilla',
        create: 'Crear Bot',
        options: {
          basic: 'Básico — Hola Mundo',
          loop: 'Bucle — Tarea repetitiva',
          requests: 'Bot HTTP — Librería Requests',
          blank: 'Blank',
        },
      },
      deleteBot: {
        title: '// Eliminar Bot',
        delete: 'Eliminar Definitivamente',
      },
      editDescription: {
        title: '// Editar Descripción',
        label: 'Descripción',
        placeholder: '¿Qué hace este bot?',
      },
    },
    messages: {
      nameRequired: 'El nombre del bot es obligatorio',
      duplicateName: 'Ya existe un bot con ese nombre',
      botDeleted: 'Bot eliminado',
      descriptionUpdated: 'Descripción actualizada',
      containerStoppedByUser: 'Contenedor detenido por el usuario',
      fileSaved: (fileName) => `${fileName} guardado`,
      saveError: (message) => `Error al guardar: ${message}`,
      botCreated: (botName) => `Bot "${botName}" creado`,
      botAlreadyRunning: (botName) => `${botName} ya está en ejecución`,
      containerStarted: (containerId) => `Contenedor iniciado: ${containerId}`,
      stopAllSuccess: (count) => `${count} bot${count !== 1 ? 's' : ''} detenido${count !== 1 ? 's' : ''}`,
      stopAllPartial: (stopped, failed) => `${stopped} detenidos, ${failed} con error`,
      deleteConfirmation: (botName) =>
        `Esto eliminará permanentemente a ${botName} y todos sus archivos. Esta acción no se puede deshacer.`,
    },
    status: {
      card: statusCardLabels,
    },
  };
}());
